// AUTO-GENERATED by scripts/codegen_ts.exs — DO NOT EDIT

// --- Method param/result interfaces ---

export interface SessionStartParams {
  /** Model to use. Defaults to config default. */
  model?: { id: string; provider: string };
  /** System prompt for the agent. */
  systemPrompt?: string;
  /** Working directory. Defaults to server cwd. */
  workingDir?: string;
  /** Tool names to enable. */
  tools?: string[];
  /** MCP server configurations. */
  mcpServers?: Record<string, unknown>[];
  /** If true, enable session persistence. */
  session?: boolean;
}

export interface SessionStartResult {
  /** The new session's unique ID. */
  sessionId: string;
  /** Paths of loaded context files. */
  contextFiles: string[];
  /** Names of discovered skills (not yet loaded). */
  availableSkills: string[];
  /** Names of connected MCP servers. */
  mcpServers: string[];
  /** Erlang node name of the server (for debugging). */
  nodeName: string;
}

export interface AgentPromptParams {
  /** Target session ID. */
  sessionId: string;
  /** The user's prompt text. */
  text: string;
}

export type AgentPromptResult = Record<string, never>;

export interface AgentSteerParams {
  /** Target session ID. */
  sessionId: string;
  /** The steering message. */
  text: string;
}

export type AgentSteerResult = Record<string, never>;

export interface AgentAbortParams {
  /** Target session ID. */
  sessionId: string;
}

export type AgentAbortResult = Record<string, never>;

export interface AgentStateParams {
  /** Target session ID. */
  sessionId: string;
}

export interface AgentStateResult {
  /** Session ID. */
  sessionId: string;
  /** One of: idle, running, streaming. */
  status: string;
  /** Current model. */
  model: { id: string; provider: string; thinkingLevel: string };
  /** Number of messages in history. */
  messageCount: number;
  /** Active tool names. */
  tools: string[];
}

export type SessionListParams = Record<string, never>;

export interface SessionListResult {
  /** Array of {id, title, modified}. */
  sessions: Record<string, unknown>[];
}

export interface SessionBranchParams {
  /** Target session ID. */
  sessionId: string;
  /** Message ID to branch from. */
  entryId: string;
}

export type SessionBranchResult = Record<string, never>;

export interface SessionCompactParams {
  /** Target session ID. */
  sessionId: string;
  /** Number of recent messages to keep. Default: 10. */
  keepRecent?: number;
}

export type SessionCompactResult = Record<string, never>;

export interface ModelsListParams {
  /** Optional list of direct providers to include (e.g. ["anthropic", "openai"]). */
  providers?: string[];
}

export interface ModelsListResult {
  /** Array of {id, name, provider, supports_thinking}. */
  models: Record<string, unknown>[];
}

export interface ModelSetParams {
  /** Target session ID. */
  sessionId: string;
  /** Model ID to switch to. */
  modelId: string;
  /** Reasoning effort: off, low, medium, high. */
  thinkingLevel?: string;
}

export interface ModelSetResult {
  /** The new active model. */
  model: { id: string; provider: string; thinkingLevel: string };
}

export interface ThinkingSetParams {
  /** Target session ID. */
  sessionId: string;
  /** Reasoning effort: off, low, medium, high. */
  level: string;
}

export interface ThinkingSetResult {
  /** The new thinking level. */
  thinkingLevel: string;
}

export type AuthStatusParams = Record<string, never>;

export interface AuthStatusResult {
  /** True if a valid token exists. */
  authenticated: boolean;
}

export type AuthLoginParams = Record<string, never>;

export interface AuthLoginResult {
  /** Code for the user to enter. */
  userCode: string;
  /** URL to visit. */
  verificationUri: string;
  /** Device code for polling. */
  deviceCode: string;
  /** Polling interval in seconds. */
  interval: number;
}

export interface TasksListParams {
  /** Target session ID. */
  sessionId: string;
}

export interface TasksListResult {
  /** Array of task objects. */
  tasks: Record<string, unknown>[];
}

export type SettingsGetParams = Record<string, never>;

export interface SettingsGetResult {
  /** Map of setting key-value pairs. */
  settings: Record<string, unknown>;
}

export interface SettingsSaveParams {
  /** Map of setting key-value pairs to save. */
  settings: Record<string, unknown>;
}

export interface SettingsSaveResult {
  /** The full settings after merge. */
  settings: Record<string, unknown>;
}

export interface ClientConfirmParams {
  /** Session this confirmation belongs to. */
  sessionId: string;
  /** Short title for the confirmation dialog. */
  title: string;
  /** Detailed message to show. */
  message: string;
  /** Available actions (e.g., ["allow", "deny", "allow_session"]). */
  actions: string[];
}

export interface ClientConfirmResult {
  /** The user's chosen action. */
  action: string;
}

export interface ClientInputParams {
  /** Session this input request belongs to. */
  sessionId: string;
  /** Prompt to display to the user. */
  prompt: string;
  /** If true, input should be masked (e.g., API keys). */
  sensitive?: boolean;
}

export interface ClientInputResult {
  /** The user's input. */
  text: string;
}

// --- Agent event types ---

export interface AgentStartEvent {
  type: "agentStart";
}

export interface AgentEndEvent {
  type: "agentEnd";
  /** Cumulative token usage for the session. */
  usage?: { completionTokens: number; contextWindow: number; currentContextTokens: number; promptTokens: number; totalTokens: number };
}

export interface AgentAbortEvent {
  type: "agentAbort";
}

export interface MessageStartEvent {
  type: "messageStart";
}

export interface MessageDeltaEvent {
  type: "messageDelta";
  /** The text fragment. */
  delta: string;
}

export interface ThinkingStartEvent {
  type: "thinkingStart";
}

export interface ThinkingDeltaEvent {
  type: "thinkingDelta";
  /** The thinking text fragment. */
  delta: string;
}

export interface ToolExecutionStartEvent {
  type: "toolExecutionStart";
  /** Tool name. */
  tool: string;
  /** Unique call identifier. */
  callId: string;
  /** Tool arguments. */
  args: Record<string, unknown>;
  /** Human-readable summary of the invocation. */
  meta: string;
}

export interface ToolExecutionEndEvent {
  type: "toolExecutionEnd";
  /** Tool name. */
  tool: string;
  /** Unique call identifier. */
  callId: string;
  /** Tool execution result. May include optional output or error string fields. */
  result: { ok: boolean };
}

export interface TurnEndEvent {
  type: "turnEnd";
  /** The assistant's message text. */
  message: string;
}

export interface ErrorEvent {
  type: "error";
  /** Error description. */
  reason: string;
}

export interface ContextDiscoveredEvent {
  type: "contextDiscovered";
  /** Paths of discovered context files. */
  files: string[];
}

export interface SkillLoadedEvent {
  type: "skillLoaded";
  /** Skill name. */
  name: string;
  /** Skill description. */
  description: string;
}

export interface SubAgentEventEvent {
  type: "subAgentEvent";
  /** The call_id of the parent sub_agent tool invocation. */
  parentCallId: string;
  /** The sub-agent's session ID. */
  subSessionId: string;
  /** The wrapped agent event from the sub-agent (contains a type field and event-specific data). */
  inner: Record<string, unknown>;
}

export interface UsageUpdateEvent {
  type: "usageUpdate";
  /** Current token usage snapshot. */
  usage: { completionTokens: number; contextWindow: number; currentContextTokens: number; promptTokens: number; totalTokens: number };
}

export interface StatusUpdateEvent {
  type: "statusUpdate";
  /** Brief human-readable status. */
  message: string;
}


export type AgentEvent =
  | AgentStartEvent
  | AgentEndEvent
  | AgentAbortEvent
  | MessageStartEvent
  | MessageDeltaEvent
  | ThinkingStartEvent
  | ThinkingDeltaEvent
  | ToolExecutionStartEvent
  | ToolExecutionEndEvent
  | TurnEndEvent
  | ErrorEvent
  | ContextDiscoveredEvent
  | SkillLoadedEvent
  | SubAgentEventEvent
  | UsageUpdateEvent
  | StatusUpdateEvent;

// --- Method constants ---

export const Methods = {
  SESSION_START: "session/start" as const,
  AGENT_PROMPT: "agent/prompt" as const,
  AGENT_STEER: "agent/steer" as const,
  AGENT_ABORT: "agent/abort" as const,
  AGENT_STATE: "agent/state" as const,
  SESSION_LIST: "session/list" as const,
  SESSION_BRANCH: "session/branch" as const,
  SESSION_COMPACT: "session/compact" as const,
  MODELS_LIST: "models/list" as const,
  MODEL_SET: "model/set" as const,
  THINKING_SET: "thinking/set" as const,
  AUTH_STATUS: "auth/status" as const,
  AUTH_LOGIN: "auth/login" as const,
  TASKS_LIST: "tasks/list" as const,
  SETTINGS_GET: "settings/get" as const,
  SETTINGS_SAVE: "settings/save" as const,
  CLIENT_CONFIRM: "client/confirm" as const,
  CLIENT_INPUT: "client/input" as const,
} as const;

// --- Helper types ---

export interface TokenUsage {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
  contextWindow: number;
  currentContextTokens: number;
}

export interface ToolResult {
  ok: boolean;
  output?: string;
  error?: string;
}

export interface ConfirmRequest {
  sessionId: string;
  title: string;
  message: string;
  actions: string[];
}

export interface InputRequest {
  sessionId: string;
  prompt: string;
  sensitive?: boolean;
}

// --- Method type mapping ---

export interface MethodTypes {
  "session/start": { params: SessionStartParams; result: SessionStartResult };
  "agent/prompt": { params: AgentPromptParams; result: AgentPromptResult };
  "agent/steer": { params: AgentSteerParams; result: AgentSteerResult };
  "agent/abort": { params: AgentAbortParams; result: AgentAbortResult };
  "agent/state": { params: AgentStateParams; result: AgentStateResult };
  "session/list": { params: SessionListParams; result: SessionListResult };
  "session/branch": { params: SessionBranchParams; result: SessionBranchResult };
  "session/compact": { params: SessionCompactParams; result: SessionCompactResult };
  "models/list": { params: ModelsListParams; result: ModelsListResult };
  "model/set": { params: ModelSetParams; result: ModelSetResult };
  "thinking/set": { params: ThinkingSetParams; result: ThinkingSetResult };
  "auth/status": { params: AuthStatusParams; result: AuthStatusResult };
  "auth/login": { params: AuthLoginParams; result: AuthLoginResult };
  "tasks/list": { params: TasksListParams; result: TasksListResult };
  "settings/get": { params: SettingsGetParams; result: SettingsGetResult };
  "settings/save": { params: SettingsSaveParams; result: SettingsSaveResult };
  "client/confirm": { params: ClientConfirmParams; result: ClientConfirmResult };
  "client/input": { params: ClientInputParams; result: ClientInputResult };
}
